# Generated by Django 4.2.3 on 2024-05-07 17:17

from django.db import migrations, models
import media_example.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', upload_to='images/', width_field='image_width')),
                ('image_height', models.IntegerField()),
                ('image_width', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='file_field',
            field=models.FileField(upload_to=media_example.models.user_grouped_file_path),
        ),
    ]
