# Generated by Django 4.2.3 on 2024-05-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_example', '0002_imageexamplemodel_alter_examplemodel_file_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(upload_to='images/')),
                ('file_field', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='file_field',
            field=models.FileField(upload_to='files/'),
        ),
    ]
